!accelerate launch $MAIN_DIR/diffusers/examples/dreambooth/train_dreambooth.py \
  --image_captions_filename \
  --pretrained_model_name_or_path="$MODELT_NAME" \
  --instance_data_dir="$INSTANCE_DIR" \
  --output_dir="$OUTPUT_DIR" \
  --instance_prompt="" \
  --seed=$Seed \
  --resolution=512 \
  --mixed_precision="fp16" \
  --sample_batch_size=1 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=2e-6 \
  --use_8bit_adam \
  --lr_scheduler="polynomial" \
  --center_crop \
  --lr_warmup_steps=0 \
  --max_train_steps=$Training_Steps
